server:
  port: 9007

spring:
  application:
    name: mysite-search

  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 192.168.89.100:9300
      cluster-name: my-es
  elasticsearch:
    rest:
      uris: http://192.168.89.100:9200

  rabbitmq:
    host: 127.0.0.1

swagger:
  show: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true