server:
  port: 9009

spring:
  application:
    name: mysite-sms

  rabbitmq:
    host: 127.0.0.1


swagger:
  show: true

aliyun:
  sms:
    accessKeyId: LTAI4GHTj6KG5gJjmU7jBjh5
    accessKeySecret: cjpRIsWtNoSseuPGYPtByKKxdwfFRa
    template_code: SMS_216404109
    sign_name: 发送短息验证码

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true