server:
  port: 12000

spring:
  application:  
    name: mysite-config #指定服务名

  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/sinz/mysite.git

  rabbitmq:
    host: 192.168.89.137

management:
  endpoint:
    web:
      exposure:
        include: bus-refresh
