server: 
  port: 9006

spring:
  application:
    name: mysite-spit

  data:
    mongodb:
      host: 192.168.89.137
      port: 27017
      database: spitdb

  redis:
    host: 192.168.89.137

  rabbitmq:
    host: 127.0.0.1

swagger:
  show: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true